import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://todomvc.com/examples/react/dist/');
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('Buy Groceries');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('Rest');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('Go shopping');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('Eating');
  await page.getByTestId('text-input').press('Enter');
  await page.getByRole('listitem').filter({ hasText: 'Buy Groceries' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await expect(page.getByTestId('todo-list').getByText('Eating')).toBeVisible();
  await page.getByText('Go shopping').click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('123');
  await page.getByTestId('text-input').press('Enter');
  await page.getByRole('button', { name: '×' }).click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('button', { name: 'Clear completed' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByText('Rest').click();
  await page.getByTestId('todo-list').getByTestId('text-input').fill('Rest stop');
  await page.getByText('Rest').click();
  await page.getByText('Rest').dblclick();
  await page.getByTestId('todo-list').getByTestId('text-input').fill('Rest stop');
  await page.getByTestId('todo-list').getByTestId('text-input').press('Enter');
  await expect(page.getByTestId('todo-list')).toContainText('Go shoppinggg');
  await page.locator('html').click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('สวัสดี');
  await page.getByTestId('text-input').press('Enter');
  await page.getByRole('button', { name: '×' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByTestId('toggle-all').check();
  await page.getByTestId('toggle-all').uncheck();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByTestId('toggle-all').check();
  await page.goto('https://todomvc.com/examples/react/dist/#/');
  await page.getByTestId('toggle-all').uncheck();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByTestId('toggle-all').check();
  await page.goto('https://todomvc.com/examples/react/dist/#/');
  await page.getByTestId('toggle-all').uncheck();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByTestId('footer').click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Rest stop' }).getByTestId('todo-item-toggle').check();
  await page.goto('https://todomvc.com/examples/react/dist/#/');
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByTestId('todo-item-toggle').check();
  await page.goto('https://todomvc.com/examples/react/dist/#/');
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('button', { name: 'Clear completed' }).click();
});